# Generated by Django 4.2.1 on 2023-06-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_acccount_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acccount',
            new_name='Account',
        ),
    ]
