# Generated by Django 4.2.1 on 2023-07-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_orders_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
