# Generated by Django 4.2.1 on 2023-10-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acctnumber', models.CharField(max_length=200)),
                ('accttype', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
